[package]
name = "ssd1680-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal = "1.0.0"
embedded-hal-async = { version = "1.0.0", optional = true }


[features]
async = ["embedded-hal-async"]
